[package]
name = "egui-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
btleplug = "0.11.7"
eframe = "0.29.1"
futures = "0.3.31"
rand = "0.8.5"
tokio = { version="1.42.0", features=["full"] }
uuid = "1.11.0"
